import {
  APP_UPGRADE_STATUS,
  CONVERSATION_STATUS,
  DOCUMENT_INDEXING_MODE,
  DOCUMENT_STATUS,
  DOCUMENT_TYPE,
  GROUNDED_ANSWER_CONFIDENCE,
  KNOWLEDGE_LIBRARY_STATUS,
  MESSAGE_STATUS,
  PARSE_STATUS,
  REPORT_STATUS,
  RUN_STATUS,
  WORKSPACE_LIBRARY_SUBSCRIPTION_STATUS,
} from "./domain";

export const DEFAULT_DOCUMENT_STATUS = DOCUMENT_STATUS.UPLOADING;
export const DEFAULT_DOCUMENT_TYPE = DOCUMENT_TYPE.OTHER;
export const DEFAULT_KNOWLEDGE_LIBRARY_STATUS = KNOWLEDGE_LIBRARY_STATUS.ACTIVE;
export const DEFAULT_WORKSPACE_LIBRARY_SUBSCRIPTION_STATUS =
  WORKSPACE_LIBRARY_SUBSCRIPTION_STATUS.ACTIVE;
export const DEFAULT_DOCUMENT_INDEXING_MODE = DOCUMENT_INDEXING_MODE.FULL;
export const DEFAULT_PARSE_STATUS = PARSE_STATUS.QUEUED;
export const DEFAULT_CONVERSATION_STATUS = CONVERSATION_STATUS.ACTIVE;
export const DEFAULT_MESSAGE_STATUS = MESSAGE_STATUS.COMPLETED;
export const DEFAULT_REPORT_STATUS = REPORT_STATUS.DRAFT;
export const DEFAULT_RUN_STATUS = RUN_STATUS.QUEUED;
export const DEFAULT_APP_UPGRADE_STATUS = APP_UPGRADE_STATUS.COMPLETED;
export const DEFAULT_GROUNDED_ANSWER_CONFIDENCE = GROUNDED_ANSWER_CONFIDENCE.LOW;

export const DEFAULT_AGENT_MAX_TURNS = 6;
export const DEFAULT_AUTO_REFRESH_INTERVAL_MS = 5_000;
export const DEFAULT_CONVERSATION_STREAM_POLL_INTERVAL_MS = 700;
export const DEFAULT_QUEUE_JOB_RETENTION_LIMIT = 100;
export const DEFAULT_RETRIEVAL_RUN_TOP_K = 6;
export const DEFAULT_SEARCH_WORKSPACE_KNOWLEDGE_TOP_K = 8;
export const MAX_SEARCH_WORKSPACE_KNOWLEDGE_TOP_K = 20;
export const DEFAULT_SEARCH_STATUTES_TOP_K = 5;
export const MAX_SEARCH_STATUTES_TOP_K = 10;
export const DEFAULT_SEARCH_WEB_GENERAL_TOP_K = 5;
export const MAX_SEARCH_WEB_GENERAL_TOP_K = 10;
export const DEFAULT_STATUTES_JURISDICTION = "CN";
export const DEFAULT_FETCH_SOURCE_PARAGRAPH_LIMIT = 50;
export const DEFAULT_EMBEDDING_BATCH_SIZE = 16;
export const DEFAULT_DASHSCOPE_EMBEDDING_BATCH_SIZE = 10;
export const DEFAULT_QDRANT_COLLECTION_NAME = "knowledge_chunks";
export const DEFAULT_HASH_VECTOR_SIZE = 256;
export const DEFAULT_QUERY_CANDIDATE_LIMIT = 36;
export const DEFAULT_QUERY_CANDIDATE_MULTIPLIER = 6;
