type ValueOf<T> = T[keyof T];

export const ASSISTANT_MCP_SERVER_NAME = "assistant";
export const ASSISTANT_TOOL = {
  SEARCH_WORKSPACE_KNOWLEDGE: "search_workspace_knowledge",
  READ_CITATION_ANCHOR: "read_citation_anchor",
  SEARCH_STATUTES: "search_statutes",
  SEARCH_WEB_GENERAL: "search_web_general",
  FETCH_SOURCE: "fetch_source",
  CREATE_REPORT_OUTLINE: "create_report_outline",
  WRITE_REPORT_SECTION: "write_report_section",
} as const;
export const ASSISTANT_TOOL_VALUES = [
  ASSISTANT_TOOL.SEARCH_WORKSPACE_KNOWLEDGE,
  ASSISTANT_TOOL.READ_CITATION_ANCHOR,
  ASSISTANT_TOOL.SEARCH_STATUTES,
  ASSISTANT_TOOL.SEARCH_WEB_GENERAL,
  ASSISTANT_TOOL.FETCH_SOURCE,
  ASSISTANT_TOOL.CREATE_REPORT_OUTLINE,
  ASSISTANT_TOOL.WRITE_REPORT_SECTION,
] as const;
export type AssistantToolName = ValueOf<typeof ASSISTANT_TOOL>;

export const ASSISTANT_MCP_TOOL_PREFIX = `mcp__${ASSISTANT_MCP_SERVER_NAME}__`;
export const ASSISTANT_COMPAT_TOOL_PREFIX = `${ASSISTANT_MCP_SERVER_NAME}__`;
export const ASSISTANT_MCP_TOOL = {
  SEARCH_WORKSPACE_KNOWLEDGE: `${ASSISTANT_MCP_TOOL_PREFIX}${ASSISTANT_TOOL.SEARCH_WORKSPACE_KNOWLEDGE}`,
  READ_CITATION_ANCHOR: `${ASSISTANT_MCP_TOOL_PREFIX}${ASSISTANT_TOOL.READ_CITATION_ANCHOR}`,
  SEARCH_STATUTES: `${ASSISTANT_MCP_TOOL_PREFIX}${ASSISTANT_TOOL.SEARCH_STATUTES}`,
  SEARCH_WEB_GENERAL: `${ASSISTANT_MCP_TOOL_PREFIX}${ASSISTANT_TOOL.SEARCH_WEB_GENERAL}`,
  FETCH_SOURCE: `${ASSISTANT_MCP_TOOL_PREFIX}${ASSISTANT_TOOL.FETCH_SOURCE}`,
  CREATE_REPORT_OUTLINE: `${ASSISTANT_MCP_TOOL_PREFIX}${ASSISTANT_TOOL.CREATE_REPORT_OUTLINE}`,
  WRITE_REPORT_SECTION: `${ASSISTANT_MCP_TOOL_PREFIX}${ASSISTANT_TOOL.WRITE_REPORT_SECTION}`,
} as const;
export type AssistantMcpToolName = ValueOf<typeof ASSISTANT_MCP_TOOL>;

export const ASSISTANT_ALLOWED_TOOL_NAMES = [
  ASSISTANT_MCP_TOOL.SEARCH_WORKSPACE_KNOWLEDGE,
  ASSISTANT_MCP_TOOL.READ_CITATION_ANCHOR,
  ASSISTANT_MCP_TOOL.SEARCH_STATUTES,
  ASSISTANT_MCP_TOOL.SEARCH_WEB_GENERAL,
  ASSISTANT_MCP_TOOL.FETCH_SOURCE,
  ASSISTANT_MCP_TOOL.CREATE_REPORT_OUTLINE,
  ASSISTANT_MCP_TOOL.WRITE_REPORT_SECTION,
] as const;

export function isAssistantToolName(value: string): value is AssistantToolName {
  return ASSISTANT_TOOL_VALUES.includes(value as AssistantToolName);
}

export function normalizeAssistantToolName(toolName: string) {
  return toolName
    .replace(new RegExp(`^${ASSISTANT_MCP_TOOL_PREFIX}`), "")
    .replace(new RegExp(`^${ASSISTANT_COMPAT_TOOL_PREFIX}`), "")
    .trim();
}
